import { SavedStatement } from '../types/finance';

export const DEMO_SEPTEMBER_2026: SavedStatement = {
  id: 'a1b2c3d4-e5f6-47a8-9b0c-1d2e3f4a5b6c',
  created_at: '2026-09-24T05:30:00.000Z',
  file_name: 'Habib_Bank_Statement_Sept_2026.pdf',
  period_label: 'September 2026',
  currency: 'PKR',
  closing_balance: 918000,
  total_debit: 1377000,
  total_credit: 1450000,
  result: {
    status: 'success',
    reference_id: 'a1b2c3d4-e5f6-47a8-9b0c-1d2e3f4a5b6c',
    period_label: 'September 2026',
    currency: 'PKR',
    opening_balance: 845000,
    closing_balance: 918000,
    total_credit: 1450000,
    total_debit: 1377000,
    summary: 'Cash flow remained positive throughout September with a net operational surplus of PKR 73,000. Core client retainers provided steady income inflows of PKR 1,450,000. Payroll and facilities constituted the majority of expenses at 64% of total debits. Software infrastructure costs experienced a 24% uptick due to annual cloud renewals, while utility charges normalized.',
    summary_ur: 'ستمبر کے دوران کیش فلو مثبت رہا اور 73,000 روپے کی خالص بچت حاصل ہوئی۔ کلائنٹ ریٹینرز کی مدد سے کل 1,450,000 روپے کی آمدنی ہوئی۔ تنخواہوں اور دفتری کرایوں پر کل اخراجات کا 64 فیصد خرچ ہوا۔ سالانہ کلاؤڈ سروسز کی تجدید کی وجہ سے سافٹ ویئر کے اخراجات میں 24 فیصد اضافہ دیکھا گیا جبکہ یوٹیلیٹی بل معمول کے مطابق رہے۔',
    categories: [
      { name: 'Salaries & Payroll', amount: 580000, percentage: 42.1, transaction_count: 5 },
      { name: 'Office Rent & Facilities', amount: 300000, percentage: 21.8, transaction_count: 2 },
      { name: 'Software & Infrastructure', amount: 185000, percentage: 13.4, transaction_count: 6 },
      { name: 'Logistics & Supply Chain', amount: 145000, percentage: 10.5, transaction_count: 4 },
      { name: 'Utility Bills', amount: 95000, percentage: 6.9, transaction_count: 3 },
      { name: 'Professional Services', amount: 72000, percentage: 5.2, transaction_count: 4 },
    ],
    transactions: [
      { date: '2026-09-02', description: 'TechVentures Retainer Payment', category: 'Client Revenue', type: 'credit', amount: 650000 },
      { date: '2026-09-03', description: 'K-Electric Commercial Power Bill', category: 'Utility Bills', type: 'debit', amount: 68000 },
      { date: '2026-09-04', description: 'AWS EMEA Cloud Hosting Renewals', category: 'Software & Infrastructure', type: 'debit', amount: 82000 },
      { date: '2026-09-05', description: 'Sui Northern Gas Commercial Meter', category: 'Utility Bills', type: 'debit', amount: 15000 },
      { date: '2026-09-06', description: 'Gulberg Corporate Towers Monthly Lease', category: 'Office Rent & Facilities', type: 'debit', amount: 280000 },
      { date: '2026-09-08', description: 'Express Freight & Local Courier Dispatch', category: 'Logistics & Supply Chain', type: 'debit', amount: 45000 },
      { date: '2026-09-10', description: 'Apex Retailers Project Milestone 2', category: 'Client Revenue', type: 'credit', amount: 500000 },
      { date: '2026-09-11', description: 'Google Workspace Enterprise Annual Seats', category: 'Software & Infrastructure', type: 'debit', amount: 48000 },
      { date: '2026-09-13', description: 'Building Maintenance & Security Levies', category: 'Office Rent & Facilities', type: 'debit', amount: 20000 },
      { date: '2026-09-14', description: 'Legal Counsel Corporate Retainer', category: 'Professional Services', type: 'debit', amount: 35000 },
      { date: '2026-09-15', description: 'Atlas Logistics Cargo Shipment', category: 'Logistics & Supply Chain', type: 'debit', amount: 52000 },
      { date: '2026-09-16', description: 'PTCL High-Speed Fiber Internet', category: 'Utility Bills', type: 'debit', amount: 12000 },
      { date: '2026-09-18', description: 'Audit & Tax Advisory Fee', category: 'Professional Services', type: 'debit', amount: 25000 },
      { date: '2026-09-19', description: 'Figma Organization Seats Renewal', category: 'Software & Infrastructure', type: 'debit', amount: 26000 },
      { date: '2026-09-20', description: 'Mid-Month Retainer Alpha Consulting', category: 'Client Revenue', type: 'credit', amount: 300000 },
      { date: '2026-09-21', description: 'Inventory Warehousing Fuel Surcharge', category: 'Logistics & Supply Chain', type: 'debit', amount: 24000 },
      { date: '2026-09-22', description: 'Inventory Warehousing Fuel Surcharge', category: 'Logistics & Supply Chain', type: 'debit', amount: 24000 }, // Repeated payment for test
      { date: '2026-09-23', description: 'GitHub Enterprise Subscription', category: 'Software & Infrastructure', type: 'debit', amount: 16000 },
      { date: '2026-09-25', description: 'Staff Bi-Weekly Operational Advance', category: 'Salaries & Payroll', type: 'debit', amount: 60000 },
      { date: '2026-09-26', description: 'Notion Team Workspace Enterprise', category: 'Software & Infrastructure', type: 'debit', amount: 13000 },
      { date: '2026-09-27', description: 'Corporate Graphic & Printing Vendor', category: 'Professional Services', type: 'debit', amount: 12000 },
      { date: '2026-09-28', description: 'Executive & Senior Engineering Salaries', category: 'Salaries & Payroll', type: 'debit', amount: 320000 },
      { date: '2026-09-28', description: 'Core Operations & Support Staff Salaries', category: 'Salaries & Payroll', type: 'debit', amount: 200000 },
    ],
  },
};

export const DEMO_AUGUST_2026: SavedStatement = {
  id: 'f9e8d7c6-b5a4-4321-9876-543210fedcba',
  created_at: '2026-08-25T04:15:00.000Z',
  file_name: 'Habib_Bank_Statement_Aug_2026.pdf',
  period_label: 'August 2026',
  currency: 'PKR',
  closing_balance: 845000,
  total_debit: 1195000,
  total_credit: 1320000,
  result: {
    status: 'success',
    reference_id: 'f9e8d7c6-b5a4-4321-9876-543210fedcba',
    period_label: 'August 2026',
    currency: 'PKR',
    opening_balance: 720000,
    closing_balance: 845000,
    total_credit: 1320000,
    total_debit: 1195000,
    summary: 'August produced robust cash reserves with net operating gains of PKR 125,000. Client retainers were received punctually. Overhead expenditures remained conservative throughout the summer operating cycle with minimal discretionary spending.',
    summary_ur: 'اگست میں کیش کے ذخائر مضبوط رہے اور 125,000 روپے کا خالص منافع حاصل ہوا۔ کلائنٹ کی تمام ادائیگیاں بروقت موصول ہوئیں۔ گرمیوں کے دورانیے میں غیر ضروری اخراجات کو مؤثر طور پر قابو میں رکھا گیا۔',
    categories: [
      { name: 'Salaries & Payroll', amount: 550000, percentage: 46.0, transaction_count: 5 },
      { name: 'Office Rent & Facilities', amount: 300000, percentage: 25.1, transaction_count: 2 },
      { name: 'Software & Infrastructure', amount: 148000, percentage: 12.4, transaction_count: 4 },
      { name: 'Logistics & Supply Chain', amount: 98000, percentage: 8.2, transaction_count: 3 },
      { name: 'Utility Bills', amount: 64000, percentage: 5.4, transaction_count: 3 },
      { name: 'Professional Services', amount: 35000, percentage: 2.9, transaction_count: 2 },
    ],
    transactions: [
      { date: '2026-08-01', description: 'TechVentures Retainer Payment', category: 'Client Revenue', type: 'credit', amount: 620000 },
      { date: '2026-08-03', description: 'K-Electric Commercial Power Bill', category: 'Utility Bills', type: 'debit', amount: 42000 },
      { date: '2026-08-05', description: 'Gulberg Corporate Towers Monthly Lease', category: 'Office Rent & Facilities', type: 'debit', amount: 280000 },
      { date: '2026-08-08', description: 'AWS EMEA Cloud Hosting Standard', category: 'Software & Infrastructure', type: 'debit', amount: 65000 },
      { date: '2026-08-10', description: 'Apex Retailers Project Milestone 1', category: 'Client Revenue', type: 'credit', amount: 450000 },
      { date: '2026-08-12', description: 'Building Maintenance & Security', category: 'Office Rent & Facilities', type: 'debit', amount: 20000 },
      { date: '2026-08-14', description: 'Atlas Logistics Inland Dispatch', category: 'Logistics & Supply Chain', type: 'debit', amount: 48000 },
      { date: '2026-08-16', description: 'PTCL High-Speed Fiber Internet', category: 'Utility Bills', type: 'debit', amount: 12000 },
      { date: '2026-08-18', description: 'Google Workspace Cloud Suite', category: 'Software & Infrastructure', type: 'debit', amount: 48000 },
      { date: '2026-08-20', description: 'Alpha Consulting Monthly Fee', category: 'Client Revenue', type: 'credit', amount: 250000 },
      { date: '2026-08-22', description: 'Corporate Legal Retainer', category: 'Professional Services', type: 'debit', amount: 35000 },
      { date: '2026-08-24', description: 'Figma Workspace Renewal', category: 'Software & Infrastructure', type: 'debit', amount: 25000 },
      { date: '2026-08-25', description: 'Regional Courier Handling Fee', category: 'Logistics & Supply Chain', type: 'debit', amount: 50000 },
      { date: '2026-08-27', description: 'Sui Northern Gas Commercial', category: 'Utility Bills', type: 'debit', amount: 10000 },
      { date: '2026-08-28', description: 'Staff Salaries August Disbursement', category: 'Salaries & Payroll', type: 'debit', amount: 550000 },
    ],
  },
};
